function I_dJr_G = I_dJr_G_fun(in1,in2)
%I_dJr_G_fun
%    I_dJr_G = I_dJr_G_fun(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Nov-2023 19:33:42

I_dJr_G = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
